In [10]:
import pandas as pd
import numpy as np

In [32]:
#read in data
df = pd.read_csv('Life_Expectancy_Data.csv',sep=r'\s*,\s*', engine='python')
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [34]:
#remove categorical data
df = df._get_numeric_data()

#create numpy matrices
X = df.drop('Life expectancy',axis=1).to_numpy()
y = df['Life expectancy'].to_numpy()

#initialising weights
theta = np.zeros(df.shape[1])

n=df.shape[0]

#parameters
epsilon = 0.1
learning_rate = 0.1

In [36]:
df.head()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,2015,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,2014,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,2013,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,2012,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,2011,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [37]:
print(X)
print(y)

[[2.015e+03 2.630e+02 6.200e+01 ... 1.730e+01 4.790e-01 1.010e+01]
 [2.014e+03 2.710e+02 6.400e+01 ... 1.750e+01 4.760e-01 1.000e+01]
 [2.013e+03 2.680e+02 6.600e+01 ... 1.770e+01 4.700e-01 9.900e+00]
 ...
 [2.002e+03 7.300e+01 2.500e+01 ... 1.300e+00 4.270e-01 1.000e+01]
 [2.001e+03 6.860e+02 2.500e+01 ... 1.700e+00 4.270e-01 9.800e+00]
 [2.000e+03 6.650e+02 2.400e+01 ... 1.120e+01 4.340e-01 9.800e+00]]
[65.  59.9 59.9 ... 44.8 45.3 46. ]